DOC_DIR?=/home/ronan/Documents/git/ccp4/docs/projects/multislice
MD?=${DOC_DIR}/pyMultislice.md #&1 #STDOUT

#slice_lib_main :
#	g++ slicelib_main.cpp ${TEMSIM}/slicelib.o -I${TEMSIM} -o ${BIN}
doc_multislice :
	pydocmd simple multislice++ >${MD}
