DOC_DIR?=/home/tarik/Documents/git/ccp4/docs/projects/multislice
MD?=${DOC_DIR}/pyMultislice.md #&1 #STDOUT

slice_lib_main :
	g++ temsim/slicelib_main.cpp bin/obj/slicelib.o -I temsim -o bin/slice_main
# doc_multislice :
# 	pydocmd simple multislice++ >${MD}
